---
title: "Tentative STT 2860 Course Schedule - Fall 2024"
output:
  html_document:
    css: ../css/style.css
    highlight: textmate
    theme: yeti
  pdf_document: default
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

________________________________

### General Notes: {-}

```{block, note-text, type='rmdnote'}
1.  Please bring a notebook and pencil to every class.
2.  The principal documents for this course are [R for Data Science (2e)](https://r4ds.hadley.nz/) (R4DS), and [Statistical Inference via Data Science](https://moderndive.com/) (MD)
3. [QUARTO cheat sheet](https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf)
```


_________

## Week 1: (Aug 19, 21, 23) {-}


* Before the first class meeting, read Chapter 1 (Getting Started with Data in R) of [MD](https://moderndive.com/1-getting-started.html)---pgs 1-20

* Read [Chapter 1](https://r4ds.hadley.nz/data-visualize) Data Visualization of R4DS.

* Read [What is Data Science](https://www.datacamp.com/blog/what-is-data-science-the-definitive-guide).

* Watch [Getting to Know Your Data in R](https://www.youtube.com/watch?v=W3D-JSPExXo)

```{block, EX1, type='rmdexercise'}
* Answer **Exercises 1-4 ** in chapter 1 of R4DS in an electronic document.  After R-Scripts are introduced, your answers will be transferred to an R-Script and eventually to a Quarto document. If you have set up Git and your PAT (see directions week 4), you may want to accept the Quarto book with files for each Chapter of the exercises by clicking [here](https://classroom.github.com/a/7dJZzUjQ). 

* Complete the **Intro to Basics** chapter of _Introduction to R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Aug 20

* Complete the **Vectors** chapter of _Introduction to R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Aug 22

* Complete the **Matrices** chapter of _Introduction to R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Aug 23
```

* Become familiar with the Appstate [RStudio/POSIT workbench](https://mathr.appstate.edu/) server. You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.





 
```{block, week1optional, type='rmdoptional'}
#### Optional {-}
*  _Introduction to R_ [slides](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/IntroToR.html)

* Watch Paul the Octopus [clip](https://www.youtube.com/watch?v=3ESGpRUMj9E) (61 seconds).

* You may want to install [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), [zotero](https://www.zotero.org), and optionally [$LaTeX$](http://www.ctan.org/starter) on your personal computer. If you do, you will want to follow Jenny Bryan's excellent advice for [installing R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html) and [installing Git](http://stat545-ubc.github.io/git01_git-install.html).  Jenny's advice is also in chapters 6 and 7 of [Happy Git and GitHub for the useR](http://happygitwithr.com/).  Note: [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), and [$LaTeX$](http://www.ctan.org/starter) are installed on the [Appstate RStudio](https://mathr.appstate.edu/) server.

* Watch the following videos as appropriate:

* [Install R on Mac (2 min)](https://www.youtube.com/watch?v=lJxVRgiX-ik)    

* [Install R for Windows (3 min)](https://www.youtube.com/watch?v=LII6of-5Odw)    

* [Install R and RStudio on Windows (5 min)](https://www.youtube.com/watch?v=eD07NznguA4)  



```

______________

## Week 2: (Aug 26, 28, 30) {-}

* Read [Chapter 2](https://r4ds.hadley.nz/workflow-basics) Workflow: basics of R4DS.

```{block, EX2, type='rmdexercise'}
* Answer **Exercises 5-8** in chapter 1 of R4DS in an electronic document.  After R-Scripts are introduced, your answers will be transferred to an R-Script and eventually to a Quarto document.  If you have set up Git and your PAT (see directions week 4), you may want to accept the Quarto book with files for each Chapter of the exercises by clicking [here](https://classroom.github.com/a/7dJZzUjQ).   

* Complete the **Factors** chapter of _Introduction to R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Aug 26

* Complete the **Data Frames** chapter of _Introduction to R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Aug 28

* Complete the **Lists** chapter of _Introduction to R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Aug 30
```




```{block, week2optional, type='rmdoptional'}
#### Optional {-}

* Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)

* Review [Five Named Graphs](../Quarto/Alpha5NG.html)
```

__________________


## Week 3: (Sep 4, 6) {-}

* Read [Chapter 3](https://r4ds.hadley.nz/data-transform) Data transformation of R4DS.

```{block, EX3, type='rmdexercise'}
* Answer **Exercises 9-12** in chapter 1 of R4DS in an electronic document.  After R-Scripts are introduced, your answers will be transferred to an R-Script and eventually to a Quarto document. If you have set up Git and your PAT (see directions week 4), you may want to accept the Quarto book with files for each Chapter of the exercises by clicking [here](https://classroom.github.com/a/7dJZzUjQ). 

* Complete the **Introduction** chapter of _Introduction to Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 4

* Complete the **Aesthetics** chapter of _Introduction to Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 6
```




```{block, week3optional, type='rmdoptional'}
#### Optional {-}

* Watch [Selecting Variables Using `dplyr` in R](https://www.youtube.com/watch?v=vDgP7J1qMCI)

* Watch [Filtering Observations Using `dplyr` in R](https://www.youtube.com/watch?v=KWs8VNeWlbE)

* Watch [Arranging Your Data Using `dplyr` in R](https://www.youtube.com/watch?v=BN9-zPuM-2g)

* Watch [Adding New Columns Using `dplyr` in R](https://www.youtube.com/watch?v=stNOP4B1aGE)

* Watch [Creating Summary Statistics Using `dplyr` in R](https://www.youtube.com/watch?v=PAE8oaC0vtk)

* Watch [Practicing your Tidyverse Skills: Advanced Filters with Dplyr](https://www.youtube.com/watch?v=w5veSzXK1jw)

* Watch [Practicing Your Tidyverse Skills: `if_else()` Functions with `dplyr`](https://www.youtube.com/watch?v=-j5Hbwua0fE)

* Watch [Practicing your Tidyverse Skills: `case_when()` Functions with `dplyr`](https://www.youtube.com/watch?v=22KMfxZgCqE)

* Posit [Cheat Sheets](https://posit.co/resources/cheatsheets/)

* Work through chapter 5 (Using `ggplot2`) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)


```

___________

## Week 4: (Sep 9, 11, 13) {-}

* Read Chapter 1 [Why Git? Why GitHub?](https://happygitwithr.com/big-picture) of Happy Git With `R`.

* Read [Chapter 4](https://r4ds.hadley.nz/workflow-style) Workflow: code style of R4DS.

* Watch [What is Reproducibility?](https://www.youtube.com/watch?v=j4PjMdfXfH4)

* Watch [Tenets of Reproducibility](https://www.youtube.com/watch?v=1uJuB5nKfrc)

* Watch [Project Management Foundations](https://www.youtube.com/watch?v=elMvykwA-Fo)

```{block, EX4, type='rmdexercise'}
* Answer **Exercises 13-16** in chapter 1 of R4DS in an R-Script or Quarto document. If you have set up Git and your PAT (see directions week 4), you may want to accept the Quarto book with files for each Chapter of the exercises by clicking [here](https://classroom.github.com/a/7dJZzUjQ). 

* Complete the **Geometries** chapter of _Introduction to Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 11

* Complete the **Themes** chapter of _Introduction to Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 13
```



We will walk through everything outlined below in class.  If you want to complete the setup before class that is fine.    

* Sign-up for a free account on [GitHub](https://github.com).  When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **firstnamelastname** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinguishing characteristic in your username.  

* Introduce yourself to Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git)

* Cache your credentials and set up a personal access token (PAT) by following the directions in [HappyGitWithR](https://happygitwithr.com/https-pat).

* TL;DR the chapters in Happy Git With R --- follow this document to [Set up Git and GitHub](https://alanarnholt.github.io/STT3850/Handouts/setup.html)

* [VIDEO of the setup process](https://drive.google.com/file/d/1L-v9qAVHWtvXOTYjY8wvedH5VyzmeQeL/view?usp=drive_link)

* [VIDEO of how to accept and clone the assignment](https://drive.google.com/file/d/1JUag-0U-reD_JcKHvez50I_4R-CCMUMt/view?usp=drive_link)



```{block, week4optional, type='rmdoptional'}
#### Optional {-}

* Read the [Git and GitHub](http://r-pkgs.had.co.nz/git.html) chapter from Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/)

* Brian Caffo's take on [R IDEs](https://www.youtube.com/watch?v=O2UFfiGdGFA)

* Work through chapter 1 (Git and GitHub) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/).  Make sure RStudio is set up to communicate with Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git.html) for introducing yourself to Git.

```

__________________



## Week 5: (Sep 16, 18, 20) {-}


* Read [Chapter 5](https://r4ds.hadley.nz/data-tidy) Data tidying of R4DS.

* Watch [Combining Datasets Using `dplyr` in R](https://www.youtube.com/watch?v=kLgZYO3tcYA)

* Watch [Hello, Quarto: A world of Possibilities (for Reproducible Publishing)](https://www.youtube.com/watch?v=Qrz2rUWM-uY)

* Watch [Binding Rows and Columns Using `dplyr` in R](https://www.youtube.com/watch?v=EaJgIW3J15Q)

* Watch [Practicing Your Tidyverse Skills: Combining Data Frames](https://www.youtube.com/watch?v=st-MQY6pWeY)

* Read [Chapter 28](https://r4ds.hadley.nz/quarto) Quarto of R4DS.

* Read [Chapter 29](https://r4ds.hadley.nz/quarto-formats) Quarto formats of R4DS.

* [Welcome to Quarto](https://quarto.org/)

```{block, EX5, type='rmdexercise'}
* Answer **Exercises 17-20** in chapter 1 of R4DS in an R-Script or Quarto document. If you have set up Git and your PAT (see directions week 4), you may want to accept the Quarto book with files for each Chapter of the exercises by clicking [here](https://classroom.github.com/a/7dJZzUjQ).  

* Complete the **Statistics** chapter of _Intermediate Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 16

* Complete the **Coordinates** chapter of _Intermediate Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 18
```

* In class we will walk through creating and publishing a [web site](https://quarto.org/docs/websites/) with Quarto.

_______________

## Week 6: (Sep 23, 25, 27) {-}


* Read [Chapter 6](https://r4ds.hadley.nz/workflow-scripts) Workflow: scripts and projects of R4DS.

```{block, EX6, type='rmdexercise'}

* Transfer all previously completed exercises from chapter 1 of R4DS into the GitHub classroom provided Quarto book.  Accept the Quarto book by clicking [here](https://classroom.github.com/a/7dJZzUjQ). 

* Answer **Exercises 1-4** in chapter 2 of R4DS in the GitHub classroom provided Quarto document.  

* Complete the **Facets** chapter of _Intermediate Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 23

* Complete the **Best Practices** chapter of _Intermediate Data Visualization with ggplot2_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 25
```



```{block, week6optional, type='rmdoptional'}
#### Optional {-}

* Work on [Is this Discrimination?](../Rmarkdown/ClassAssignment.html)

* Some ideas for how to answer the [Is this Discrimination?](../Rmarkdown/discrimination.html)
```

_____________


## Week 7: (Sep 30, Oct 2, 4) {-}

* Read [Chapter 7](https://r4ds.hadley.nz/data-import) Data import of R4DS.

```{block, EX7, type='rmdexercise'}
* Answer **Exercises 1-4** in chapter 3 of R4DS in the GitHub classroom provided Quarto document.  

* Complete the **Data Wrangling** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Sep 30

* Complete the **Data Visualization** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 2
```

* Start Project # 1 --- Due Oct 25 NLT 5:00 PM

```{block, Project1, type='rmdnote'}
* Project # 1: [Duplicate Amber Thomas's work on bicycle sharing](https://amber.rbind.io/2016/11/10/bicyclesseattle/) - Use your own formatting and publish your analysis on your personal GitHub webpage.
* For additional ideas see: 
  1. Todd Schneider's blog [post](http://toddwschneider.com/posts/taxi-vs-citi-bike-nyc/)
  2. [bikedata](https://ropensci.org/blog/blog/2017/10/17/bikedata) package
```

```{block, week7optional, type='rmdoptional'}
#### Optional {-}

* Read chapter 3 (Data Wrangling) of [MD](https://moderndive.com/3-wrangling.html) --- pgs 65-96

* Read chapter 4 (Data Importing and "Tidy" Data) of [MD](https://moderndive.com/4-tidy.html) --- pgs 99-117

* Work through chapter 3 (Starting with Data) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

* Work through chapter 4 (Data Manipulation) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

```



___________


## Week 8: (Oct 7, 9, 11) {-}

* Read [Chapter 8](https://r4ds.hadley.nz/workflow-help) Workflow: getting help of R4DS.

```{block, EX8, type='rmdexercise'}
* Answer  **Exercises 5-8 and 16** in chapter 3 of R4DS in the GitHub classroom provided Quarto document.  

* Complete the **Grouping and Summarizing** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 7

* Complete the **Types of Visualizations** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 9
```


_______________

## Fall Break: Oct 14 -- 15

_______________

## Week 9: (Oct 16, 18) {-}

* Read [Chapter 9](https://r4ds.hadley.nz/layers) Layers of R4DS.

```{block, EX9, type='rmdexercise'}
* Answer **Exercises 1-4** in chapter 9 of R4DS in the GitHub classroom provided Quarto document.  

* Complete the **Transforming Data with dplyr** chapter of _Data Manipulation with dplyr_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 16

* Complete the **Aggregating Data** chapter of _Data Manipulation with dplyr_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 18
```





```{block, week9optional, type='rmdoptional'}
#### Optional {-}

* Read chapter 3 (Data Wrangling) of [MD](https://moderndive.com/3-wrangling.html) --- pgs 65-96

* Read chapter 4 (Data Importing and "Tidy" Data) of [MD](https://moderndive.com/4-tidy.html) --- pgs 99-117

* Work through chapter 3 (Starting with Data) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

* Work through chapter 4 (Data Manipulation) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)
* In-class work on [dplyr-CH1-handout](https://classroom.github.com/a/dS2Ac6LI)

* In-class work on [dplyr-CH2-handout](https://classroom.github.com/a/1UqoDdSM) 
* In-class work on [dplyr-CH3-handout](https://classroom.github.com/a/EzmZUAMy) 
* In-class work on [dplyr-CH4-handout](https://classroom.github.com/a/MH5tJXf6) 

```

___________________________


## Week 10: (Oct 21, 23, 25) {-}

* Read [Chapter 10](https://r4ds.hadley.nz/eda) Exploratory data analysis of R4DS.

```{block, EX10, type='rmdexercise'}
* Answer **Exercises 7-10** in chapter 9 of R4DS in the GitHub classroom provided Quarto document.  
```



* Project # 1 --- Due Oct 25 NLT 5:00 PM

_______________________


## Week 11: (Oct 28, 30, Nov 1) {-}

* Read [Chapter 11](https://r4ds.hadley.nz/communication) Communication of R4DS.

```{block, EX11, type='rmdexercise'}

* Complete the **Custom ggplot2 Themes** chapter of _Communicating with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 29

* Complete the **Creating a Custom and Unique Visualization** chapter of _Communicating with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Oct 30
```

* Start Project # 2 --- Due Dec 11 NLT 11:00 AM

```{block, Project2, type='rmdnote'}
* Project # 2: Pick a data set (get instructor's approval of the data NLT Nov 4).  Munge the data, create graphs, communicate your findings on your web page. 
```


_____________________


## Week 12: (Nov 4, 6, 8) {-}


```{block, EX12, type='rmdexercise'}
* Complete the **Introduction to RMarkdown** chapter of _Communicating with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Nov 4

* Complete the **Customizing your RMarkdown Report** chapter of _Communicating with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Nov 6

* Work on Project # 2
```

______________________



## Week 13: (Nov 11, 13, 15) {-}


```{block, EX13, type='rmdexercise'}
* Complete the **Data cleaning and summarizing with dplyr** chapter of _Exploratory Data Analysis with R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Nov 11

* Complete the **Data visualization with ggplot2** chapter of _Exploratory Data Analysis with R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Nov 13

* Work on Project # 2
``` 

_________________

## Week 14: (Nov 18, 20, 22) {-}


```{block, EX14, type='rmdexercise'}
* Complete the **Tidy modeling with broom** chapter of _Exploratory Data Analysis with R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Nov 18

* Complete the **Joining and tidying** chapter of _Exploratory Data Analysis with R_ --- [DataCamp](https://app.datacamp.com/groups/stt2860-f24/assignments) --- Due NLT 5:00 pm Nov 20

* Work on Project # 2
``` 

________________________

## Thanksgiving Break (Nov 27 -- 29)
________________________


## Week 15: (Nov 25 & Dec 2) {-}

```{block, EX15, type='rmdexercise'}
* Work on Project # 2
``` 

_____________________________________


## Final Exam --- Dec 11: 11:00 am - 1:30 pm



________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________